### ISSUE TITLE
Solving SDEs using a complex parameter p object 

### ISSUE THREAD

**Issue by rvignolo** [SciML/diffeqpy#54]
Hi @ChrisRackauckas, 

I believe I have an interesting problem for you or anyone else who wants to join the conversation. We are building a program that solves a System of Stochastic Differential Equations as underlying problem. In that context, we are using `DifferentialEquations.jl` because it has state of the art algorithms for that purpose. However, for some reasons that do not matter, we are bounded to code in Python, not it Julia, so we use `diffeqpy` to connect to `DifferentialEquations.jl`.

That being said, I want to be really detailed so we can be in the same page. Please try to follow me, it's worth it. Let's begin.

The user describes the problem to solve by means of a high-level plain-text input file containing, among other things:
  - algebraic expressions,
  - data for function interpolation.

This means that the user cannot program in python, she provides the instructions in a simple input file, like if she was writing on a piece of paper.

Let's say that the user wants to simulate a process given by the following SDE:
```
dS(t) = f(S, t) * dt + g(S, t) * dW(t)
```
where the auxiliary functions `f` and `g` are given by algebraic expressions:
```
f(x, y) = kappa(y) * (theta(y) - x)
g(x, y) =  sigma(y) * sqrt(x)
```
and `kappa`, `theta` and `sigma` are functions given by 1D interpolated data (obtained somehow by calibration methods).
In this case, the input file might be given by:
```yaml
Function kappa(x):
  xdata: [ provide pointwise data ]
  fdata: [ provide pointwise data ]
  method: cubic

Function theta(x):
  xdata: [ provide pointwise data ]
  fdata: [ provide pointwise data ]
  method: cubic

Function sigma(x):
  xdata: [ provide pointwise data ]
  fdata: [ provide pointwise data ]
  method: cubic

Function f(x,y) = kappa(y) * (theta(y) - x)
Function g(x,y) = sigma(y) * sqrt(x)

Process X:
  x0:         sqrt(pi)
  drift:     f(X_t, t)
  diffusion: g(X_t, t)
```
Just in case you are wondering what is `X_t`, it is an special variable that takes the value of the process X at each time t. Also, check out that the auxiliary functions `f` and `g` are defined using variables `x` and `y` but then they are evaluated at the special variable `X_t` and time `t` (this is also a special variable that takes the time value). 

To parse this input, we use Sympy and other strategies (for handling interpolators). At the end of the parsing, the `drift` and `diffusion` of the process `X` are expressions that can be evaluated by means of Python functions:
```python
def drift(X_t, t):
    return kappa(t) * (theta(t) - X_t)

def diffusion(X_t, t):
    return sigma(t) * sqrt(X_t)
```
and `kappa`, `theta` and `sigma` are SciPy interpolators for example. Now, the definition of the SDE problem is given by:
```python
sde = de.SDEProblem(f_for_julia, g_for_julia, u0, tspan, p)
```
where ```f_for_julia``` and ```g_for_julia``` are simple to understand but they actually involve a lot of things, so writing them on Julia is not an straightforward task. For example, we have:
```python
def f_for_julia(du, u, p, t):

        # set time variable value to solver time value
        p.get_variable('t').set_value(t)

        # set all processes variables to solver estimation
        for i, process in enumerate(p.processes):
            process.var.set_value(u[i])

        # once all variables are set, compute derivatives
        for i, process in enumerate(p.processes):
            du[i] = process.expr_drift.eval()
```
In this function, many things happen:
  1. parameter `p` is an instance of a class that haves a lot of information, not just a list of constant numbers.
  2. set the variable t value to the solver t value. This is because we will evaluate expressions depending on `t` variable.
  3. set all processes variables (for example, `X_t`) to the solver value. This is because we will evaluate expressions depending `X_t` variable.
  4. evaluate the drift expression provided in the input file for each process. In this case, this means the evaluation of `f(X_t, t)`. Variable `t` has been set to the solver value in item 1. and variable `X_t` has been set to the solver value in item 2.

In this last item 3, the evaluation of the expression `f(X_t, t)` involves calling the python function `drift` described above with the correct values of `X_t` and `t`. In that function, there are calls to  SciPy interpolators.

So, at this point I am able to describe my problem. Even though everything works as expected, it takes a lot of time. I believe every time the Python function `f_for_julia` is called from Julia for the computation of a Monte Carlo time step involves a lot of time. In [this ](http://juliadiffeq.org/2018/04/30/Jupyter.html)page, you describe a similar problem in section `Performance: Ordinary Differential Equations (ODEs)`, where it takes `111.4923981380125 sec` to solve an ODE system. If you instead use `jul_f = de.eval(""" ... """)`, the involved time decreases drastically and you get to solve the same problem in `0.8532032310031354 sec`.

The thing is that in that example, is really simple to migrate your python `f` function to Julia, while in my case, `f_for_julia` cannot be migrated to Julia so easily. 

What would you do? Would you use the `ModellingToolkit .jl` package to migrate my expressions to Julia and provide them in a big Julia script for `jul_f = de.eval(""" ... """)`, where `...` contains the lines of the script? Of course, I would also have to migrate the interpolators, etc.

Thank you very much for everything, I will be waiting for your response.

Ramiro

**Comment by ChrisRackauckas** [comment]
>What would you do? Would you use the ModellingToolkit .jl package to migrate my expressions to Julia and provide them in a big Julia script for jul_f = de.eval(""" ... """), where ... contains the line of the script? Of course, I would also have to migrate the interpolators, etc.

In theory you could use ModelingToolkit from the Python side to generate Julia code for you. That would be a very performant way to handle this, but I haven't tried it yet, but I plan to update the README with an example of that. However, the issue that you're going to run into is that it can currently only generate ODE systems. Adding the generation of SDE systems is a little more difficult since it needs to understand the Brownian terms and then prove linearity of the Brownian terms to then build the drift and diffusion functions: not necessarily hard, but something I haven't gotten around to yet. 

Also, yes, the interpolation functions would need to get Juliaified as well otherwise they'll be a bottleneck: maybe there's a direct translation from what you have to something in DataInterpolations.jl?

This is all the right question to ask and the right direction to go though. I think that as we push this to have a deeper connection with Python, we will be making more use of ModelingToolkit from the Python side so that way we can generate the code, rather than asking for a Python function (slow) or Julia eval (a very poor way to support the high speed version).

**Comment by rvignolo** [comment]
@ChrisRackauckas thanks for your kind reply, really useful. I have some comments:

1. I will be waiting for that example that you are planning to provide in the README.md or maybe you could forward it to me as it is.
2. Yes, I realized that `ModelingToolkit.jl` handles only ODE systems. For SDEs, maybe you can avoid proving linearity for now (if that is the complicated part).
3. Thanks for `DataInterpolations.jl.` Maybe you can recommend me another package that supports 2 dimensional interpolation as well? N-Dimensional would be great also (at least, bilinear interpolation). 
4. Imagine that I want to simulate a stochastic process with a diffusion `sigma(t)` given by either an interpolated function or an algebraic expression such as `sin(t)`. With `ModelingToolkit.jl` I would be able to migrate from Python the algebraic expression easily but the other case would require a little work (migrate the interpolator and then make sure that the Julia expression points to the interpolator function). A more complicated case would be the simulation of a process with a diffusion given by:
    ```
    Integral(sigma(t), t, 0, T), 
    ```
    with `T` a known constant? This is just an example. I would like to know if integrals, derivatives and other functionals could be easily supported by `ModelingToolkit.jl` framework. Please, notice that in this case it would involve either a numerical integration (when `sigma(t)` is given by an interpolator) or a symbolic integration of `sigma(t)` (when `sigma(t)` is given by an algebraic expression). Also, notice that in this case the output of the integral would just be a constant, so I could compute it Python and the migrate to Julia. But in the general case, I would like to handle functionals that yield to expressions depending on the time or on processes values, i.e., the `u` and `t` parameters in the drift and diffusion functions that we provide to the SDE problem in `DifferentialEquations.jl`.

Item 4 is the most important one :)

Thanks in advance!

**Comment by rvignolo** [comment]
What I would like to know is if it is possible that `ModelingToolkit.jl` support additional objects like:
  - Interpolated functions,
  - Symbolic and numeric integration and differentiation. 
  - other functions such as piecewise(), min(), max()
  - other functionals such as sum(), prod()
because in all the examples that I have seen there are only algebraic expressions that depend on symbols.

Thanks!

**Comment by ChrisRackauckas** [comment]
Interpolated functions: Yes, every variable can be a function, and you can use this feature to make any function things work. In Pumas.jl, we use this feature to put DataInterpolations.jl interpolated functions into a ModelingToolkit.jl model and generate the equations.

Symbolic Integration: That requires writing rewrite rules, which is why we are pairing with Simplify.jl

Numeric Integration: That requires just adding a new primative function for calls to Quadrature.jl and the like. That wouldn't be more than a few lines of code to implement, and would be a good quick PR.

Symbolic Differentiation: There's quite a few examples of this in the docs and such already

Numeric differentiation: If you register a function call to AD it'll just work

Other functions such as ...: Just `@register` missing functions, and possibly define better symbolic derivatives of them than the defaults. For your examples:

piecewise: just use ifelse
min and max: just register it, and add a derivative overload that uses ifelse?
sum and prod: just register it and add derivative definitions using a generated function that reads in the number of arguments

>because in all the examples that I have seen there are only algebraic expressions that depend on symbols.

Variables can be tensors as well (recent feature), and so you can use that to do a lot of fancy thing in a "mathematically simpler" way

------------------------------------------------
Applied Mathematics Instructor, Massachusetts Institute of Technology
Senior Research Analyst, University of Maryland, Baltimore, School of Pharmacy, Center for Translational Medicine
On 10/21/2019 12:02:04 PM, Rami Vignolo <notifications@github.com> wrote:
What I would like to know is if it is possible that ModelingToolkit.jl support additional objects like:
* Interpolated functions,
* Symbolic and numeric integration and differentiation.
* other functions such as piecewise(), min(), max()
* other functionals such as sum(), prod()
because in all the examples that I have seen there are only algebraic expressions that depend on symbols.
Thanks!

**Comment by rvignolo** [comment]
okay, this is perfect, I will implement all these features.

I am working from the python side and I have already managed to migrate many features of my drift and diffusion functions to Julia code so I can run SDE Ensemble problems fast. 

As always, thank you very much for your help.

quick question: Automatic Differentiation works if you want to differentiate an interpolated function? I was wondering that...

**Comment by ChrisRackauckas** [comment]
>quick question: Automatic Differentiation works if you want to differentiate an interpolated function? I was wondering that...

No, but if your interpolation is something from something like DataInterpolations.jl, you can just register the derivative to be the derivative of the interpolant. (If that's what you mean by interpolated function)
