### ISSUE TITLE
Custom sysimage building to remove compile times

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/diffeqpy#56]
If everything is always acting on float arrays, we could probably remove almost all of the compile times just be precompiling the standard solve calls with Float64s. pyjulia seems to allow for this:

https://github.com/JuliaPy/pyjulia/blob/master/src/julia/sysimage.py

so we could add a precompile function. But @tkf do I need to take care to not overwrite other sysimages? Could this be done better by having a separate Julia installed with pyjulia?

**Comment by tkf** [comment]
At the moment there is no direct method to add custom modules to the system image generated by PyJulia (beyond just PyCall).  But it should be possible... in principle.

ref: https://github.com/JuliaPy/pyjulia/issues/311

> If everything is always acting on float arrays, we could probably remove almost all of the compile times just be precompiling the standard solve calls with Float64s.

I think one challenge might be to generate enough `precompile` statements.  Last time I tried PackageCompiler.jl, it was not super robust.

> do I need to take care to not overwrite other sysimages?

PyJulia does not replace the default system image.  It just creates a new one, since the generated system image is only usable inside Python.  So, you don't need to worry about disturbing normal `julia` usage.

OTOH, you need to manage generated system image and load it manually ATM.  This can be automated but this is a non-trivial project by itself.  (I'm thinking some thing like I do with `jlm` https://discourse.julialang.org/t/22849; or `jlm` can be integrated with PyJulia.)

**Comment by ChrisRackauckas** [comment]
Removed via v1.9 and v1.10 improvements.
