### ISSUE TITLE
Example problems giving similar but not exact match solutions.

### ISSUE THREAD

**Issue by GrandadsJumper** [SciML/diffeqpy#62]
Im running python 3.8 on a x64 system.

I have numpy, numba, julia and matplotlib imported succesfully.

The results from running the copied and pasted "Lorenz equations" & "One dimensional SDE's" problems give me the following results. 

![Lorenz_3D](https://user-images.githubusercontent.com/35103244/79784788-ac489080-833a-11ea-9d38-2e72cb03b6b7.png)
![Lorenz_2D](https://user-images.githubusercontent.com/35103244/79784791-ace12700-833a-11ea-85a6-a0cf3b1de804.png)

The general shape of the graphs follows that of the example solutions but on closer inspection is not the same. 

Has anyone came across this issue too ?

**Comment by ChrisRackauckas** [comment]
There was a small change to the step size choice algorithm about 6th months ago that caused a 1e-12 difference in some steps. However, this problem is [chaotic](https://en.wikipedia.org/wiki/Lorenz_system), so trajectories diverge exponentially fast. If you want more information on the numerical divergence of algorithms on the Lorenz attractor, check out [the Uncertainty Quantification documentation](https://docs.sciml.ai/latest/analysis/uncertainty_quantification/#Example-3:-Adaptive-ProbInts-on-the-Lorenz-Attractor-1). But yeah... a chaotic system is a fun plot but not something to look at in terms of accuracy unless you do the high fidelity UQ stuff shown there.
